[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyVoIP"
version = "2.0.0a5"
description = "PyVoIP is a pure python VoIP/SIP/RTP library."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPLv3" }
authors = [
    { name = "Tayler Porter", email = "taylerporter@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Telecommunications Industry",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Topic :: Communications :: Internet Phone",
    "Topic :: Communications :: Telephony",
]

[project.urls]
Homepage = "https://github.com/tayler6000/pyVoIP"
"Bug Tracker" = "https://github.com/tayler6000/pyVoIP/issues"
Documentation = "https://pyvoip.readthedocs.io/"

[tool.hatch.build.targets.wheel]
packages = ["pyVoIP"]

[tool.hatch.build.targets.sdist]
exclude = [
    "tests",
]

[tool.black]
line-length = 79
target-version = ['py38']
